### ISSUE TITLE
Feature Request: Toggle All Module Checkboxes

### ISSUE THREAD

**Issue by Norc** [sdenec/fvtt-uii_game-settings#4]
In the Manage Modules page, would it be possible to get a Toggle All Modules button added to the top of the list? Clicking every checkbox to test is awful (and the existing Reset all Modules button in the Edit World interface is awkward to navigate to).

**Comment by sdenec** [comment]
New button on the top (to not click it by accident when saving - trust me, testing accidents^^)!
