### ISSUE TITLE
Feature Request: Import/Export Active Module List

### ISSUE THREAD

**Issue by Norc** [sdenec/fvtt-uii_game-settings#5]
I (and other users) would love for it to be possible to export a list of modules that you have enabled, and then reimport them again.

**Example Uses**:
I have many modules installed, but I do not have them all enabled at all times. Modules that I'm still learning are installed but not checked, as are ones that I love but have not updated yet. This feature would enable me to save the list of modules that I want currently enabled, then to re-enable the correct ones again after troubleshooting.

Other users mentioned that they have only some modules that they want for GM prep, and will have a different set for gameplay.

**Comment by sdenec** [comment]
Good feature request but sadly out of my skill set. Sorry!
