### ISSUE TITLE
Feature Request: reorder buttons on the Game Settings Tab

### ISSUE THREAD

**Issue by apoapostolov** [sdenec/fvtt-uii_game-settings#6]
Allow the DM to edit a configuration order that allows him to reorder the links on the Game Settings tab, hide by removing buttons his players should not see, or set a comfortable order for himself removing those he doesn't need but mods add.

For example for myself I would like to remove the Invitation Links, and I want to put Go to Setup under Log Out, I want to hide Documentation and Community Wiki Pages I know already, and a mod called Playlist Tweaks adds Playlist Importer button there which I want to remove completely from sight.

Such configuration suggested above would allow me to reorder and hide buttons.

**Comment by sdenec** [comment]
Good feature request but sadly nothing I can provide. Sorry!
