### ISSUE TITLE
Feature Request: Toggle All Modules Back On

### ISSUE THREAD

**Issue by Norc** [sdenec/fvtt-uii_game-settings#7]
Thanks very much for implementing the toggle all modules off button, but I don't think I was quite clear enough in my request.

There was another half of my request that I was kind of implying with the word "toggle" but stupidly didn't say outright - toggling every other module off is great, but I was also hoping for a toggle all modules back on again button. It can either be the same button, or another one... not sure what is easier.

Thanks!!! This is my last major ask, I swear haha...

**Comment by sdenec** [comment]
Thy wish shall be granted! ;)
